### ISSUE TITLE
Interesting performance distribution when uploading concurrently

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry-incubator/bits-service#9]
Was doing some ad-hoc performance testing against the bits service and noticed some interesting behavior I thought I'd share. I ran some file uploads from a jumpbox, comparing how long it took to upload files straight to webdav vs webdav via the bits service. I used a single bits service VM with 2 cores. The blobstore VM also has 4 cores.

For a single 200MB upload, uploads directly to webdav took ~2.1 seconds while uploads to webdav via bits service took ~3.5 seconds. So some amount of overhead.

When I performed 16 concurrent uploads I got the following results for straight to webdav:

```
Webdav average: 1.43563
Webdav rounds:
0.33
0.46
0.62
0.77
0.86
1.02
1.16
1.38
1.50
1.58
1.79
1.91
2.05
2.20
2.63
2.71
```

For uploads to the bits service:

```
Bits average: 2.96688
Bits rounds:
2.97
2.95
2.95
2.96
2.97
2.96
2.96
2.96
2.95
2.96
2.95
2.95
2.96
2.96
2.96
3.10
```

For this case, it's interesting that all the uploads complete at once rather than a more even distribution like the direct uploads.

Additional info here: https://gist.github.com/ljfranklin/cab6b6bda9c94c2e3ddb8f9e47f89dea

**Comment by suhlig** [comment]
Thanks for the input! We have a [story in the backlog](https://www.pivotaltracker.com/story/show/121744393) to address performance and scalability and we will come back to your findings then.

**Comment by petergtz** [comment]
We have completely re-written the Bits-Service in Go last year. Since then, performance has been several hundred times better than it used to be. For details, see also https://github.com/petergtz/bitsgo/blob/master/performance-comparison.md

Furthermore, we've worked with the RelInt team on some on performance issues rooted in the interaction design between Cloud Controller and Bits-Service and fixed them. As it looks right now, Bits-Service has no performance impact on Cloud Foundry.

Closing this issue therefore. Anyone feel free to re-open, if you see need. Thanks.
